[[plugins]]
repo = 'joonty/vdebug'
hook_add = '''
    let g:vdebug_keymap = {
                \ 'run'               : '<F8>',
                \ 'run_to_cursor'     : '<F1>',
                \ 'step_over'         : '<F10>',
                \ 'step_into'         : '<F11>',
                \ 'step_out'          : '<S-F11>',
                \ 'close'             : '<F6>',
                \ 'detach'            : '<F7>',
                \ 'set_breakpoint'    : '<F9>',
                \ 'get_context'       : '<S-F12>',
                \ 'eval_under_cursor' : '<F12>',
                \ }
'''
[[plugins]]
repo = 'vim-scripts/ctrlp.vim'
hook_add = '''
    let g:ctrlp_cache_dir = expand('~/.cache/ctrlp')
    let g:ctrlp_clear_cache_on_exit = 0
    let g:ctrlp_lazy_update = 1
    let g:ctrlp_root_markers = ['Gemfile', 'pom.xml', 'build.xml']
    let g:ctrlp_max_height = 20
    let g:ctrlp_custom_ignore = {
      \ 'dir':  '\v[\/]\.(git|hg|svn)$',
      \ 'file': '\v\.(exe|so|dll)$',
      \ 'link': 'some_bad_symbolic_links',
      \ }
'''
[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
    let g:unite_enable_start_insert = 1
    nmap <leader>u [unite]
    nnoremap [unite]m :<c-u>Unite neomru/file
    nnoremap [unite]f :<c-u>Unite file_rec
    nnoremap [unite]g :<c-u>Unite file_rec/git
'''
