git clone https://github.com/cespare/vim-toml.git 
git clone https://github.com/vim-scripts/Align.git 
git clone https://github.com/Shougo/denite.nvim.git 
git clone https://github.com/mattn/emmet-vim.git 
git clone https://github.com/lambdalisue/gina.vim.git 
git clone https://github.com/cocopon/iceberg.vim.git 
git clone https://github.com/Shougo/neomru.vim.git 
git clone https://github.com/Shougo/neosnippet-snippets.git 
git clone https://github.com/Shougo/neosnippet.vim.git 
git clone https://github.com/fuenor/qfixgrep.git 
git clone https://github.com/cocopon/vaffle.vim.git 
git clone https://github.com/tpope/vim-fugitive.git 
git clone https://github.com/nathanaelkane/vim-indent-guides.git 
git clone https://github.com/thinca/vim-qfreplace.git 
git clone https://github.com/thinca/vim-quickrun.git 
git clone https://github.com/cespare/vim-toml.git 
